name: Docker Build and Run upscayl-ncnn

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: upscayl-ncnn:latest
          load: true

      - name: Run Docker container
        run: |
          docker run --name upscayl-container upscayl-ncnn:latest

      - name: Copy artifact from Docker container
        run: |
          docker cp upscayl-container:/upscayl-ncnn/build/upscayl-ncnn ./upscayl-ncnn

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: upscayl-ncnn
          path: ./upscayl-ncnn
